=== barry963/Robot_project/Botnia/runtime_folder/2002SimulatorBinaries/robocup.dtd
<!ELEMENT parameter_file (sim_world+,COMMENT*)>	
<!ELEMENT COMMENT (#PCDATA)>	
<!ELEMENT sim_world (COMMENT*, ( field | decoration | ball | wall | robot | goal | geometry)+)>	
	<!ATTLIST sim_world name CDATA #REQUIRED>		
	<!ATTLIST sim_world x_size CDATA #REQUIRED>	
	<!ATTLIST sim_world y_size CDATA #REQUIRED>		
	<!ATTLIST sim_world z_size CDATA "0">
        <!ATTLIST sim_world in_latency CDATA #IMPLIED>	
	<!ATTLIST sim_world out_latency CDATA #IMPLIED>
	<!ATTLIST sim_world frame_rate CDATA #IMPLIED>
	<!ATTLIST sim_world max_noise_radius CDATA #REQUIRED>
	<!ATTLIST sim_world max_noise_theta CDATA #REQUIRED>
<!ELEMENT geometry (COMMENT*,shape)>		
    <!ATTLIST geometry start_position CDATA #REQUIRED>
    <!ATTLIST geometry start_velocity CDATA #REQUIRED>	
<!ELEMENT appearance (COMMENT*)>		
    <!ATTLIST appearance fill_color CDATA #REQUIRED>		
	<!ATTLIST appearance edge_color CDATA #REQUIRED>		
	<!ATTLIST appearance edge_thickness CDATA #REQUIRED>			
<!ELEMENT robot (geometry,appearance*,kicker*,dribbler*,COMMENT*)>		
	<!ATTLIST robot name CDATA #REQUIRED>		
	<!ATTLIST robot id CDATA #REQUIRED>                
	<!ATTLIST robot team CDATA #REQUIRED>		
	<!ATTLIST robot elasticity CDATA #IMPLIED>	
    <!ATTLIST robot mass CDATA #REQUIRED>	
	<!ATTLIST robot inherits CDATA #IMPLIED>	
<!ELEMENT wall (geometry,appearance*,COMMENT*)>		
	<!ATTLIST wall name CDATA #REQUIRED>	
	<!ATTLIST wall elasticity CDATA #REQUIRED>		
	<!ATTLIST wall inherits CDATA #IMPLIED>	
<!ELEMENT ball (geometry,appearance*,COMMENT*)>		
	<!ATTLIST ball mass CDATA #REQUIRED>
        <!ATTLIST ball name CDATA #IMPLIED>
	<!ATTLIST ball id CDATA #IMPLIED>                
	<!ATTLIST ball team CDATA #IMPLIED>	
	<!ATTLIST ball kinetic_friction CDATA #REQUIRED>	
	<!ATTLIST ball static_friction CDATA #REQUIRED>		
	<!ATTLIST ball elasticity CDATA #REQUIRED>		
	<!ATTLIST ball inherits CDATA #IMPLIED>	       
<!ELEMENT goal (geometry,appearance*,COMMENT*)>	
	<!ATTLIST goal team CDATA #REQUIRED>	
	<!ATTLIST goal inherits CDATA #IMPLIED>	
<!ELEMENT field (geometry,appearance*,COMMENT*)>		
	<!ATTLIST field kinetic_friction CDATA #REQUIRED>	
	<!ATTLIST field static_friction CDATA #REQUIRED>		
	<!ATTLIST field elasticity CDATA #REQUIRED>		
	<!ATTLIST field inherits CDATA #IMPLIED>                
<!ELEMENT decoration (geometry,appearance*)>       
 <!ELEMENT line (COMMENT*)>				
	<!ATTLIST line length CDATA #REQUIRED>		
	<!ATTLIST line angle CDATA #REQUIRED>	        
<!ELEMENT Plane (COMMENT*)>                
	<!ATTLIST Plane length CDATA #REQUIRED>		
	<!ATTLIST Plane width CDATA #REQUIRED>	               
    <!ATTLIST Plane normalangle CDATA #IMPLIED>     
<!ELEMENT circle (COMMENT*)>               
	 <!ATTLIST circle radius CDATA #REQUIRED>
	 <!ATTLIST circle orientation CDATA #REQUIRED>     
<!ELEMENT arc (COMMENT*)>                
	<!ATTLIST arc radius CDATA #REQUIRED>		
	<!ATTLIST arc begin_angle CDATA #REQUIRED>	                
	<!ATTLIST arc end_angle CDATA #REQUIRED>        
<!ELEMENT rectangle (COMMENT*)>                
	<!ATTLIST rectangle length CDATA #REQUIRED>		
	<!ATTLIST rectangle width CDATA #REQUIRED>
    <!ATTLIST rectangle orientation CDATA #REQUIRED>	               
    <!ATTLIST rectangle height CDATA "0">     
<!ELEMENT kicker (shape,COMMENT*)>               
    <!ATTLIST kicker kick_impulse CDATA #REQUIRED>	
	<!ATTLIST kicker reset_time CDATA #REQUIRED>       
<!ELEMENT dribbler (shape,COMMENT*)> 
	<!ATTLIST dribbler stickiness CDATA #REQUIRED>       
<!ELEMENT shape (line | circle | rectangle | Plane | arc)+>

=== barry963/Robot_project/Botnia/runtime_folder/2002SimulatorBinaries/5by5.xml
<?xml version="1.0"?> <!DOCTYPE parameter_file SYSTEM "robocup.dtd"> 
<!-- RoboCup Simulator Sample XML Parameter File --><!-- Written on: December 9, 2001 -->
<!-- This file describe the existing robocup system in XML -->
<!-- It has 5 Team A robots and 5 Team B robots, a field and 2 goals-->

<parameter_file>
	<sim_world name="5X5System2002" x_size="4.0" y_size="2.0" z_size="0" out_latency="6" in_latency="5" frame_rate="60" max_noise_radius="0.5" max_noise_theta="2.5">

<!--Robots for our team --> 		

		<robot name="Team A-0" team="1" id="0" mass="2.2" elasticity=".5">
			<geometry start_position="0.15,0,0" start_velocity="0,0,0">
				<shape>
				<circle radius="0.09" orientation="3.14159"/>
				</shape>
			</geometry>
			<kicker kick_impulse="5" reset_time="0.1">
				<shape>
					<arc radius="0.09" begin_angle="-90" end_angle="90"/>
				</shape>
			</kicker>
			<dribbler stickiness="100">
				<shape>
					<arc radius="0.09" begin_angle="-90" end_angle="90"/>
				</shape>
			</dribbler>
		</robot>
		<robot name="Team A-1" team="1" id="1" mass="2.2" elasticity=".5">
			<geometry start_position="0.3,0.2,0" start_velocity="0,0,0">
				<shape>
				<circle radius="0.09" orientation="3.14159"/>
				</shape>
			</geometry>
			<kicker kick_impulse="5" reset_time="0.1">
				<shape>
					<arc radius="0.09" begin_angle="-90" end_angle="90"/>
				</shape>
			</kicker>
			<dribbler stickiness="100">
				<shape>
					<arc radius="0.09" begin_angle="-90" end_angle="90"/>
				</shape>
			</dribbler>

		</robot>
		<robot name="Team A-2" team="1" id="2" mass="2.2" elasticity=".5">
			<geometry start_position="0.3,-0.2,0" start_velocity="0,0,0">
				<shape>
				<circle radius="0.09" orientation="3.14159"/>
				</shape>
			</geometry>
			<kicker kick_impulse="5" reset_time="0.1">
				<shape>
					<arc radius="0.09" begin_angle="-90" end_angle="90"/>
				</shape>
			</kicker>
			<dribbler stickiness="100">
				<shape>
					<arc radius="0.09" begin_angle="-90" end_angle="90"/>
				</shape>
			</dribbler>
		</robot>
		<robot name="Team A-3" team="1" id="3" mass="2.2" elasticity=".5">
			<geometry start_position="1,0,0" start_velocity="0,0,0">
				<shape>
				<circle radius="0.09" orientation="3.14159"/>
				</shape>
			</geometry>
			<kicker kick_impulse="5" reset_time="0.1">
				<shape>
					<arc radius="0.09" begin_angle="-90" end_angle="90"/>
				</shape>
			</kicker>
			<dribbler stickiness="100">
				<shape>
					<arc radius="0.09" begin_angle="-90" end_angle="90"/>
				</shape>
			</dribbler>
		</robot>
		<robot name="Team A-4" team="1" id="4" mass="2.2" elasticity=".5">
			<geometry start_position="1.2,0,0" start_velocity="0,0,0">
				<shape>
				<circle radius="0.09" orientation="3.14159"/>
				</shape>
			</geometry>
			<kicker kick_impulse="5" reset_time="0.1">
				<shape>
					<arc radius="0.09" begin_angle="-90" end_angle="90"/>
				</shape>
			</kicker>
			<dribbler stickiness="100">
				<shape>
					<arc radius="0.09" begin_angle="-90" end_angle="90"/>
				</shape>
			</dribbler>
		</robot>



<!--Robots of opposite team -->

            <robot name="Team B-0" team="0" id="0" mass="2.2" elasticity=".5">
			<geometry start_position="-0.15,0,0" start_velocity="0,0,0">
				<shape>
				<circle radius="0.09" orientation="0"/>
				</shape>
			</geometry>
			<kicker kick_impulse="5" reset_time="0.1">
				<shape>
					<arc radius="0.09" begin_angle="-90" end_angle="90"/>
				</shape>
			</kicker>
			<dribbler stickiness="100">
				<shape>
					<arc radius="0.09" begin_angle="-90" end_angle="90"/>
				</shape>
			</dribbler>
		</robot>
		<robot name="Team B-1" team="0" id="1" mass="2.2" elasticity=".5">
			<geometry start_position="-0.2,0.2,0" start_velocity="0,0,0">
				<shape>
				<circle radius="0.09" orientation="0"/>
				</shape>
			</geometry>
			<kicker kick_impulse="5" reset_time="0.1">
				<shape>
					<arc radius="0.09" begin_angle="-90" end_angle="90"/>
				</shape>
			</kicker>
			<dribbler stickiness="100">
				<shape>
					<arc radius="0.09" begin_angle="-90" end_angle="90"/>
				</shape>
			</dribbler>
		</robot>
		<robot name="Team B-2" team="0" id="2" mass="2.2" elasticity=".5">
			<geometry start_position="-0.2,-0.2,0" start_velocity="0,0,0">
				<shape>
				<circle radius="0.09" orientation="0"/>
				</shape>
			</geometry>
			<kicker kick_impulse="5" reset_time="0.1">
				<shape>
					<arc radius="0.09" begin_angle="-90" end_angle="90"/>
				</shape>
			</kicker>
			<dribbler stickiness="100">
				<shape>
					<arc radius="0.09" begin_angle="-90" end_angle="90"/>
				</shape>
			</dribbler>
		</robot>
		<robot name="Team B-3" team="0" id="3" mass="2.2" elasticity=".5">
			<geometry start_position="-1,0,0" start_velocity="0,0,0">
				<shape>
				<circle radius="0.09" orientation="0"/>
				</shape>
			</geometry>
			<kicker kick_impulse="5" reset_time="0.1">
				<shape>
					<arc radius="0.09" begin_angle="-90" end_angle="90"/>
				</shape>
			</kicker>
			<dribbler stickiness="100">
				<shape>
					<arc radius="0.09" begin_angle="-90" end_angle="90"/>
				</shape>
			</dribbler>
		</robot>
		<robot name="Team B-4" team="0" id="4" mass="2.2" elasticity=".5">
			<geometry start_position="-1.2,0,0" start_velocity="0,0,0">
				<shape>
				<circle radius="0.09" orientation="0"/>
				</shape>
			</geometry>
			<kicker kick_impulse="5" reset_time="0.1">
				<shape>
					<arc radius="0.09" begin_angle="-90" end_angle="90"/>
				</shape>
			</kicker>
			<dribbler stickiness="100">
				<shape>
					<arc radius="0.09" begin_angle="-90" end_angle="90"/>
				</shape>
			</dribbler>
		</robot>

<!--Our field -->
		<field static_friction="0.34" kinetic_friction="0.3" elasticity="0">
			<geometry start_position="0,0,0" start_velocity="0,0,0">
				<shape>
				<rectangle length="2.8" width="2.3" orientation="0"/>
				</shape>
			</geometry>
		</field>

<!--Goals-->
		<goal team="0">
			<geometry start_position="-1.49,0,0" start_velocity="0,0,0">
				<shape>
				<rectangle length="0.7" width="0.18" orientation="2"/>
				</shape>
			</geometry>
		</goal>
		<goal team="1">
			<geometry start_position="1.49,0,0" start_velocity="0,0,0">
				<shape>
				<rectangle length="0.7" width="0.18" orientation="2"/>
				</shape>
			</geometry>
		</goal>
<!--Walls-->
		<wall name="Top" elasticity=".8">
			<geometry start_position="0,1.175,0" start_velocity="0,0,0">
				<shape>
				<rectangle length="2.9" width="0.05" orientation="0"/>
				</shape>
			</geometry>
		</wall>
            
		<wall name="bottom" elasticity=".8">
			<geometry start_position="0,-1.175,0" start_velocity="0,0,0">
				<shape>
				<rectangle length="2.9" width="0.05" orientation="0"/>
				</shape>
			</geometry>
		</wall>


		
		<wall name="upper_left_side" elasticity=".8">
			<geometry start_position="-1.425,0.75,0" start_velocity="0,0,0">
				<shape>
				<rectangle length="0.8" width="0.05" orientation="2"/>
				</shape>
			</geometry>
		</wall>
		<wall name="upper_right_side" elasticity=".8">
			<geometry start_position="1.425,0.75,0" start_velocity="0,0,0">
				<shape>
				<rectangle length="0.8" width="0.05" orientation="2"/>
				</shape>
			</geometry>
		</wall>
		<wall name="lower_left_side" elasticity=".8">
			<geometry start_position="-1.425,-0.75,0" start_velocity="0,0,0">
				<shape>
				<rectangle length="0.8" width="0.05" orientation="2"/>
				</shape>
			</geometry>
		</wall>
            <wall name="lower_right_side" elasticity=".8">
			<geometry start_position="1.425,-0.75,0" start_velocity="0,0,0">
				<shape>
				<rectangle length="0.8" width="0.05" orientation="2"/>
				</shape>
			</geometry>
		</wall>

		<wall name="left_goal_backside" elasticity=".8">
			<geometry start_position="-1.585,0,0" start_velocity="0,0,0">
				<shape>
				<rectangle length="0.7" width="0.01" orientation="2"/>
				</shape>
			</geometry>
		</wall>
               <wall name="right_goal_backside" elasticity=".8">
			<geometry start_position="1.585,0,0" start_velocity="0,0,0">
				<shape>
				<rectangle length="0.7" width="0.01" orientation="2"/>
				</shape>
			</geometry>
		</wall>

		<wall name="left_goal_upside" elasticity=".8">
			<geometry start_position="-1.49,0.355,0" start_velocity="0,0,0">
				<shape>
				<rectangle length="0.18" width="0.01" orientation="0"/>
				</shape>
			</geometry>
		</wall>
                <wall name="right_goal_upside" elasticity=".8">
			<geometry start_position="1.49,0.355,0" start_velocity="0,0,0">
				<shape>
				<rectangle length="0.18" width="0.01" orientation="0"/>
				</shape>
			</geometry>
		</wall>
		<wall name="left_goal_downside" elasticity=".8">
			<geometry start_position="-1.49,-0.355,0" start_velocity="0,0,0">
				<shape>
				<rectangle length="0.18" width="0.01" orientation="0"/>
				</shape>
			</geometry>
		</wall>
                <wall name="right_goal_downside" elasticity=".8">
			<geometry start_position="1.49,-0.355,0" start_velocity="1,0,0">
				<shape>
				<rectangle length="0.18" width="0.01" orientation="0"/>
				</shape>
			</geometry>
		</wall>



<!---Balls-->
            
            <ball mass="0.0483" static_friction="0.1" kinetic_friction="0.75" elasticity="0.83">
			<geometry start_position="[0,0,0]" start_velocity="0,0,0">
				<shape>
				<circle radius="0.0427" orientation="0"/>
				</shape>
			</geometry>
		</ball>



	</sim_world>
</parameter_file>
